version: '3.3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_bt
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert/server.crt:/etc/nginx/cert/server.crt
      - ./nginx/cert/server.key:/etc/nginx/cert/server.key 
    depends_on:
      - fastapi_bt
      - nextjs_bt
  nextjs_bt:
    build: ./nextjs
    container_name: nextjs_bt
    restart: always
    depends_on:
      - fastapi_bt
  fastapi_bt:
    build: ./fastapi_app
    container_name: fastapi_bt
    ports:
      - "8888:8888"
    volumes:
      - ./fastapi_app/app/:/code/app/
      - ./fastapi_app/:/code/
      - ./fastapi_app/requirements.txt:/code/requirements.txt
    environment:
      - API_KEY=akljnv13bvi2vfo0b0bw
      - BT_HOOK_URL=https://www.dryv.site/rest/63/y9hluey3m325tme5
